/**
 * Property 3: Correctitud de validación de email
 * Validates: Requirements 8.2
 * Label: "Feature: mind-and-code-landing-page, Property 3: Correctitud de validación de email"
 */

import { describe, it, expect } from 'vitest';
import fc from 'fast-check';
import { validateEmail } from '../script.js';

describe('Feature: mind-and-code-landing-page, Property 3: Correctitud de validación de email', () => {
  /**
   * **Validates: Requirements 8.2**
   *
   * For any valid email address (generated by fc.emailAddress()),
   * validateEmail must return true.
   */
  it('should return true for valid email addresses', () => {
    fc.assert(
      fc.property(
        fc.emailAddress(),
        (email) => {
          expect(validateEmail(email)).toBe(true);
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * **Validates: Requirements 8.2**
   *
   * For any string that does not contain '@',
   * validateEmail must return false.
   */
  it('should return false for strings without @', () => {
    fc.assert(
      fc.property(
        fc.string().filter((s) => !s.includes('@')),
        (str) => {
          expect(validateEmail(str)).toBe(false);
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * **Validates: Requirements 8.2**
   *
   * For any string with an empty local part (starts with @),
   * validateEmail must return false.
   */
  it('should return false for strings with empty local part', () => {
    fc.assert(
      fc.property(
        fc.domain(),
        (domain) => {
          const emailWithEmptyLocal = '@' + domain;
          expect(validateEmail(emailWithEmptyLocal)).toBe(false);
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * **Validates: Requirements 8.2**
   *
   * For any string with an empty domain part (ends with @),
   * validateEmail must return false.
   */
  it('should return false for strings with empty domain part', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 1 }).filter((s) => !s.includes('@') && !s.includes(' ')),
        (local) => {
          const emailWithEmptyDomain = local + '@';
          expect(validateEmail(emailWithEmptyDomain)).toBe(false);
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * **Validates: Requirements 8.2**
   *
   * For any string with a domain that has no dot,
   * validateEmail must return false.
   */
  it('should return false for emails with domain lacking a dot', () => {
    fc.assert(
      fc.property(
        fc.string({ minLength: 1 }).filter((s) => !s.includes('@') && !s.includes(' ')),
        fc.string({ minLength: 1 }).filter((s) => !s.includes('.') && !s.includes('@') && !s.includes(' ')),
        (local, domain) => {
          const email = local + '@' + domain;
          expect(validateEmail(email)).toBe(false);
        }
      ),
      { numRuns: 100 }
    );
  });

  /**
   * **Validates: Requirements 8.2**
   *
   * For any arbitrary string, validateEmail returns true if and only if
   * the regex /^[^\s@]+@[^\s@]+\.[^\s@]+$/ matches.
   * This verifies the function's behavior is consistent with its implementation.
   */
  it('should match expected validation logic for arbitrary strings', () => {
    fc.assert(
      fc.property(
        fc.string(),
        (str) => {
          const result = validateEmail(str);
          const regex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
          const expected = regex.test(str);
          expect(result).toBe(expected);
        }
      ),
      { numRuns: 100 }
    );
  });
});
